### ISSUE TITLE
`_book` isn't ignored from git

### ISSUE THREAD

**Issue by wjam** [ClojureBridgeLondon/workshop-content-gitbook#1]
Should probably `curl --fail --output .gitignore https://www.gitignore.io/api/vim%2Cnode%2Cmacos%2Clinux%2Cemacs%2Cwindows%2Cintellij`

**Comment by jr0cket** [comment]
_book has been added to the .gitignore file as it is a temporary directory generated by Gitbook and not part of the actual content.

https://github.com/ClojureBridgeLondon/workshop-content-gitbook/blob/master/.gitignore
