### ISSUE TITLE
Make it more obvious what the spelling mistake is on the page "Exercise: Spell Checking"

### ISSUE THREAD

**Issue by zoodor** [ClojureBridgeLondon/workshop-content-gitbook#30]
On the "Exercise: Spell Checking" page, the second sentence containing a spelling mistake to be fixed is  "coed as data as coed" - it's not necessarily clear to the student that "coed" is supposed to be "code" - it might be better to use an example that contains a more obvious misspelling.

**Comment by EwaTrzemzalska** [comment]
Do you think that "Hlleo World" will be enough?

**Comment by zoodor** [comment]
I *think* that the idea of the second example is to demonstrate that when calling `replace` that it replaces **all** occurrences of the word, not just one of them - so I think an example should be used that contains a duplicate mis-spelling.

**Comment by EwaTrzemzalska** [comment]
Allright, so "Hlleo World, Hlleo Friends" would solve that issue, right?

**Comment by jr0cket** [comment]
Interesting suggestions, how about borrowing a variation on hello friends, romans, countrymen:

ello friends. ello clojurians. ello developers around our world.

Is that obvious enough?  

We could state in the exercise that the person writing the text had a broken `h` keyboard on the keyboard and you are challenged with fixing their text?

**Comment by jr0cket** [comment]
Deployed to live.  Thank you everyone.
