### ISSUE TITLE
"Map extraction with get" page text is confusing

### ISSUE THREAD

**Issue by zoodor** [ClojureBridgeLondon/workshop-content-gitbook#32]
The text reads:

> `count`, every collection has this function. Why do you think the answer is two? `count` is returning the number of associations.

But at this point it's not clear what "answer" is being referred to - the code example is not until after the next paragraph.

It might be better to put the code example first, before this sentence. It also might read slightly more easily as something like:

> Every collection has a `count` function. Why do you think the answer is two? `count` is returning the number of associations.

**Comment by EwaTrzemzalska** [comment]
I will take care of this!
